# Generated by Django 5.0.6 on 2024-08-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysyte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='age',
            field=models.IntegerField(),
        ),
    ]
