# Generated by Django 5.0.6 on 2024-08-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysyte', '0003_course_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='count',
        ),
        migrations.RemoveField(
            model_name='course',
            name='rate',
        ),
    ]
